version: "3.8"
services:
    mongodb:
        container_name: mongodb
        build: 
            context: mongodb/
        volumes:
            - ./data/mongodata:/data/mongodata 
        ports:
        - "27017:27017"
        command: mongod
        networks:
        - elk   

    db-explorer:
        container_name: DB-explorer
        build:
            context: ../DB-explorer/
        volumes:
            - "../DB-explorer/:/code/app"
        ports:
            - "8000:80"
        command: 
            ["dotnet", "watch", "run"]
        depends_on:
            - "mongodb"
        networks:
          - elk

    db-initializer:
        container_name: DB-initializer
        build:
            context: ../DB-initializer/
        volumes:
            - "../DB-initializer/:/code/app"
        ports:
            - "8001:80"
        depends_on:
            - "mongodb"
        networks:
          - elk

networks: 
    elk:    
        driver: bridge

volumes: 
    mongodata: